export const FIRST_NAMES = [
  'Wout',
  'Mathieu',
  'Tadej',
  'Primoz',
  'Sepp',
  'Maxim',
  'Matteo',
  'Mattias',
  'Nils',
  'Jao',
  'Vincenzo',
  'Remco',
  'Taco',
  'Edoardo',
  'Tiesj',
  'Per',
  'Wilco',
  'Cian',
  'Jonas',
  'Julian',
  'Simon',
  'Axel',
  'Mikel',
  'Enric',
  'Santiago',
  'Giulio',
  'Felix',
  'Laurens',
  'Tobias',
  'Romain',
  'Geraint',
  'Nielson',
  'Pavel',
  'Magnus',
  'Lennert',
  'Lorenzo',
  'Harold',
  'Ion',
  'Giovanni',
  'Xandro',
  'Jhonatan',
  'Mauri',
  'Thymen',
  'Valentin',
  'Ruben',
  'Marc',
  'Filippo',
  'Kasper',
  'Biniam',
  'Matej',
  'Zoe',
  'Shari',
  'Jackmerius',
  'Neve',
  'Antonia',
  'Katarzyna',
  'Soraya',
  'Cecilie',
  'Fin',
  'Niamh',
  'Valentina',
  'Mavi',
  'Grace',
  'Shirin',
  'Puck',
  'Thalita',
  'Juliette',
  'Gaia',
  'Demi',
  'Lucinda',
  'Floortje',
  'Loes',
  'Marte',
  'Fem',
  'Justine',
  'Brompton',
  'Zippy',
  'Pedalicious',
  'Trekster',
  'Velociraptor',
  'Sprocket',
  'Rollover',
  'Crankshaft',
  'Turbo',
  'Girodella',
  'Bicycletta',
  'Wheely',
  'Cyclonova',
  'Lance-a-lot',
  'Racelicious',
  'Chainbreaker',
  'Pedalero',
  'Veloce',
  'Spinmaster',
  'Zestful',
  'Gustavo Vroom',
  'Riderella',
  'Wheely McFly',
  'Zippity Zoom',
  'Saddleback',
  'Fastidious',
  'Bicyclops',
  'Flintstone',
  'Pacekeeper',
  'Whirlwind',
  'Gearshift',
  'Staminator',
  "Rollin' Thunder",
  'Speedster',
  'Bikelicious',
  'Vroominator',
  'Turbocharge',
  'Crankaroo',
  'Zoomerang',
  'Windcatcher',
  'Rushmore',
  'Velozity',
  'Pedal Pusher',
  'Speedwagon',
  'Twist and Turn',
  'Dashwood',
  'Sprinticus',
  'Zoomer',
  'Bikezilla',
  'Pedal Pundit',
  'Nimblefoot',
  'Torque Master',
  'Raceface',
  'Cykel',
  'Thunderbolt',
  'Whiplash',
  'Jetstream',
  'Fastlane',
  'Cyclistopher',
  'Gearslinger',
  'Quicksilver',
  'Pedalicious',
  'Twist & Go',
  'Whirlwind',
  'Rapidfire',
  'Spin Doctor',
  'Rolling Thunder',
  'Speedy Gonzalez',
  'Flywheel',
  'Dynamo',
  'Jetsetter',
  'Sonic Boom',
  'Rider Raptor',
  'Blaze',
  'Flameout',
  'Trailblazer',
  'Power Pedaler',
  'Wheeler Dealer',
  'Speed Junkie',
  'Bikerella',
  'Drift King',
  'Wind Rider',
  'Epic Cycle',
  'Aerodynamicus',
  'Peddler',
  'Chase Me',
  'Rapid Racer',
  'Roller Coaster',
  'Cyclepath',
  'Nimble Noodles',
  'Spin Wizard',
  'Dashhound',
  'Zephyr',
];

export const LAST_NAMES = [
  'Baroncini',
  'Backstedt',
  'Lemond',
  'Realini',
  'Bradbury',
  'Chabbey',
  'Niewiadoma',
  'Vollering',
  'Kopecky',
  'Van Vleuten',
  'Vos',
  'Vas',
  'Norsgaard',
  'Rooijakkers',
  'Muzic',
  'Gigante',
  'Ghekiere',
  'Tacktheritrix',
  'Brand',
  'Labous',
  'De Jong',
  'Pieterse',
  'Ludwig',
  'Uttrup-Ludwig',
  'Squiban',
  'Markus',
  'Adegeest',
  'Kool',
  'Zana',
  'Van Aert',
  'Soler',
  "O'Connor",
  'Roglic',
  'Carapaz',
  'Mas',
  'Landa',
  'Lipowitz',
  'Kuss',
  'Gall',
  'Sivakov',
  'Benoot',
  'Alaphilippe',
  'Evenepoel',
  'Van Der Poel',
  'Asgreen',
  'Hirt',
  'Girmay',
  'Van Der Hoorn',
  'Ganna',
  'Pogacar',
  'Vingegaard',
  'Jorgenson',
  'Kelderman',
  'Lazkano',
  'Abrahamsen',
  'Hindley',
  'Healy',
  'Johannessen',
  'De Plus',
  'Madouas',
  'Ciccone',
  'Bardet',
  'Cort',
  'Mohoric',
  'Pedalstein',
  'Speedington',
  'Wheelyman',
  'Crankshaftington',
  'Trekalot',
  'Velozowski',
  'Riderbottom',
  'Zoomington',
  'Spinnerman',
  'Bikehart',
  'Sprocketsworth',
  'Dashington',
  'Bikelander',
  'Whirlwindson',
  'Zippelton',
  'Turbolet',
  'Tireflinger',
  'Cycloneberg',
  'Pedalon',
  'Gearwhiz',
  'Racestorm',
  'Blazewheel',
  'Rapidmount',
  'Cyclestorm',
  'Vroomington',
  'Fastalot',
  'Spinwheeler',
  'Girodell',
  'Trailblazerstein',
  'Flywheeler',
  'Bikemore',
  'Nimblestone',
  'Wheelephant',
  'Saddletramp',
  'Rollerman',
  'Whiplasher',
  'Velocez',
  'Peddlington',
  'Gearshifter',
  'Jetstreamer',
  'Speedwhirl',
  'Zoomerfist',
  'Wheeleton',
  'Paceplenty',
  'Bikerhaven',
  'Crankinator',
  'Sprintmaster',
  'Windrider',
  'Dashdriven',
  'Cyclenstein',
  'Flyerberg',
  'Sprockett',
  'Turbochaser',
  'Velocinator',
  'Rollersmith',
  'Swiftbottom',
  'Zoomwell',
  'Bikehartz',
  'Pedalpushman',
  'Spinberg',
  'Velocepod',
  'Fastfoot',
  'Racermore',
  'Blizzardbiker',
  'Gearslinger',
  'Rushmoreton',
  'Wheelerwick',
  'Crankfury',
  'Thunderwheels',
  'Speedwell',
  'Spinbolt',
  'Riderstorm',
  'Trailhawk',
  'Dashrider',
  'Cyclingston',
  'Torquehead',
  'Saddleworth',
  'Blitzspeed',
  'Flyaway',
  'Vroomfield',
  'Bikecraft',
  'Dashspoke',
  'Sprocketman',
  'Whirlwindfield',
  'Geargrinder',
  'Jetsetterson',
  'Paceclimber',
  'Trekfrost',
];
